### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by FranciscoHeronildo** [UnBArqDsw/2020.1_G1_Triagil#1]
# Descrição
Criação e documentação dos Rich Pictures.

## Tarefas
- [x] Rich Picture dos Enfermeiros
- [x] Rich Picture dos Pacientes
- [x] Rich Picture do Sistema

**Comment by FranciscoHeronildo** [comment]
Foi realizado o Rich Picture do Sistema e já encontra-se no nosso OneDrive

**Comment by Miguel-Alves** [comment]
Rich Picture da visão dos enfermeiros já foi desenvolvido e está disponível no drive.
