### ISSUE TITLE
Backlog do Produto

### ISSUE THREAD

**Issue by FranciscoHeronildo** [UnBArqDsw/2020.1_G1_Triagil#13]
# Descrição
Construir e documentar o backlog do projeto

**Comment by FranciscoHeronildo** [comment]
Devido a problemas internos tal tarefa foi adiada

**Comment by FranciscoHeronildo** [comment]
Deve ser feito uma revisão do backlog do triagil

**Comment by Miguel-Alves** [comment]
Nova versão atualizada do backlog já foi desenvolvida.
