### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EsioFreitas** [UnBArqDsw/2020.1_G1_Triagil#15]
**Visão geral**
Muito boa a ideia!! Gostei muito! No entanto, além da modelagem, não há documentos na wiki. Ressalto que fiquem atentos, pois a matéria vai apertando. Por fim, a forma como está organizado os arquivos de vcs me estranha um pouco. Por exemplo: “Projeto Não Orientado a Abordagens Específicas”. Ressalto que vejam a hierarquia e organize da melhor forma para avaliação de vcs.

**Comment by FranciscoHeronildo** [comment]
@EsioFreitas Obrigado pelo feedback. Acho que você quis dizer o documento de Metodologia, e valeu pela dica em relação a matéria os documentos então em andamento, acho que está sendo um grande desafio para equipe a realização da disciplina remotamente. Vou verificar melhor a hierarquia do nosso pages e deixa-lá mas coerente possível.
