### ISSUE TITLE
Correções

### ISSUE THREAD

**Issue by FranciscoHeronildo** [UnBArqDsw/2020.1_G1_Triagil#39]
# Descrição

Foi identificado erros de notação e estilos nos artefatos, que deveram ser corrigidos.

**Tarefas:**
- [ ] Corrigir rastros quebrados.
- [ ] Corrigir padrões de estilo da documentação
- [ ] Verificar e corrigir possíveis erros gramaticas.

**Comment by Natilorens** [comment]
Encontramos inconsistências em alguns documentos e decidimos reabrir essa issue.
