### ISSUE TITLE
UML Estático 

### ISSUE THREAD

**Issue by FranciscoHeronildo** [UnBArqDsw/2020.1_G1_Triagil#62]
# Descrição

Elaboração e documentação dos diagramas estático que envolvem o escopo do triagil

## Tarefas
- [x] Classe
- [x] Pacote
- [x] Componente

**Comment by deborapvilela** [comment]
Diagramas de pacotes finalizados e disponíveis no drive do grupo.

**Comment by Miguel-Alves** [comment]
Documentos concluídos e merge realizado. Issue completa
