### ISSUE TITLE
UML Dinâmicos

### ISSUE THREAD

**Issue by FranciscoHeronildo** [UnBArqDsw/2020.1_G1_Triagil#63]
# Descrição

Elaboração e documentação dos diagramas dinâmicos  que envolvem o escopo do triagil

## Tarefas
- [ ] Sequência
- [x] Estado
- [x] Atividades
- [x] Comunicação

**Comment by FranciscoHeronildo** [comment]
UML de atividades finalizado e encontra-se no OneDrive da equipe Triagil

**Comment by vitorAlves7** [comment]
UML de estado foi finalizado e está no OneDrive da equipe

**Comment by FranciscoHeronildo** [comment]
UML de comunicação finalizado e encontra-se no OneDrive da equipe

**Comment by vitorAlves7** [comment]
Além dos diagramas feitos, foi finalizado também o diagrama de caso de uso como iniciativa extra.
